name: model-training
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  train-model:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3
      - name: Sepup Python and install requirements
      - uses: actions/setup-python@v3
        with:
            python-version: '3.9'
    - run: pip install -r requirements.txt
    - name: Train model
    - run: python src\train.py
    - name: Upload Train model
    - uses: actions/upload-artifact@v3
      with:
        name: baummethoden_lr.pickle
        path: data\models\baummethoden_lr.pickle


